[workspace]
members = [
    "crates/*",
    "frus-examples/forge/frontend/forge",
]
exclude = ["templates"]
resolver = "2"

[workspace.package]
version = "0.2.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/KalybosPro/frus"

[workspace.dependencies]
anyhow = "1"
arboard = "3"
cosmic-text = "0.19"
env_logger = "0.11"
glyphon = "0.12"
log = "0.4"
lyon = "1"
pollster = "0.3"
taffy = "0.7"
wgpu = "30"
winit = "0.30"

[workspace.dependencies.bytemuck]
version = "1"
features = ["derive"]

[workspace.dependencies.image]
version = "0.25"
features = [
    "png",
    "jpeg",
]
default-features = false

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.web-release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
inherits = "release"
strip = true
